# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppEigenProd1 <- function(Z_alles, D, SigmaInv, y, Mu) {
    .Call('_glmmLasso_RcppEigenProd1', PACKAGE = 'glmmLasso', Z_alles, D, SigmaInv, y, Mu)
}

RcppEigenProd2 <- function(D, SigmaInv) {
    .Call('_glmmLasso_RcppEigenProd2', PACKAGE = 'glmmLasso', D, SigmaInv)
}

RcppEigenProd3 <- function(W_inv_t, Z_aktuell, InvFisher2) {
    .Call('_glmmLasso_RcppEigenProd3', PACKAGE = 'glmmLasso', W_inv_t, Z_aktuell, InvFisher2)
}

RcppEigenDiagSp <- function(a) {
    .Call('_glmmLasso_RcppEigenDiagSp', PACKAGE = 'glmmLasso', a)
}

RcppEigenSpChol <- function(W_opt) {
    .Call('_glmmLasso_RcppEigenSpChol', PACKAGE = 'glmmLasso', W_opt)
}

RcppEigenSigmaInv <- function(mu) {
    .Call('_glmmLasso_RcppEigenSigmaInv', PACKAGE = 'glmmLasso', mu)
}

RcppEigenInvMa <- function(Sigma) {
    .Call('_glmmLasso_RcppEigenInvMa', PACKAGE = 'glmmLasso', Sigma)
}

